[package]
name = "kernel-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kernel-md = { path = "../kernel-md" }
kernel-store = { path = "../kernel-store" }
kernel-sync = { path = "../kernel-sync" }
notify.workspace = true

[dev-dependencies]
tempfile.workspace = true
