[package]
name = "kernel-deploy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kernel-store = { path = "../kernel-store" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
ring.workspace = true
thiserror.workspace = true
hmac.workspace = true
reqwest.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true
