[package]
name = "kernel-browser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kernel-design = { path = "../kernel-design" }
serde_json.workspace = true
reqwest.workspace = true
futures-channel.workspace = true
futures-sink.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
